name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout code  
        uses: actions/checkout@v3

      - name: Cache nimble
        id: nimble-cache
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
        if: runner.os != 'Windows'
      
      - name: Set up nimble
        uses: jiro4989/setup-nim-action@v1
      
      - name: Build
        run: nimble build -Y
      
      - name: Test
        run: nimble test -Y
      
      - name: Upload artifacts - Linux
        uses: actions/upload-artifact@v3
        with:
          name: Minecraft Asset Maker - Linux Binary
          path: MinecraftAssetMaker
        if: runner.os != 'Windows'

      - name: Upload artifacts - Windows
        uses: actions/upload-artifact@v3
        with:
          name: Minecraft Asset Maker - Windows Binary
          path: MinecraftAssetMaker.exe
        if: runner.os == 'Windows'
  
  release:
    name: Release
    
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts - Linux
        uses: actions/download-artifact@v3
        with:
          name: Minecraft Asset Maker - Linux Binary

      - name: Download artifacts - Windows
        uses: actions/download-artifact@v3
        with:
          name: Minecraft Asset Maker - Windows Binary

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            MinecraftAssetMaker
            MinecraftAssetMaker.exe
          draft: false
          prerelease: false
          generate_release_notes: true
